version: 1.0.{build}
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - projectA\libs
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
before_build:
  - nuget restore
build:
  publish_nuget: true
  project: LiveInternetFeed.sln
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
