version: 1.0.{build}
image:
  - Visual Studio 2017
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified                  # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
before_build:
  - nuget restore

platform:
  - x64
  - x86

configuration:
  - Release

build:
  publish_nuget: false
  project: LiveInternetFeed.sln
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: detailed
artifacts:
  - path: Output32

  - path: Output64

